Document: ruby-jquery-scrollto-rails
Title: Debian ruby-jquery-scrollto-rails Manual
Author: <insert document author here>
Abstract: This manual describes what ruby-jquery-scrollto-rails is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ruby-jquery-scrollto-rails/ruby-jquery-scrollto-rails.sgml.gz

Format: postscript
Files: /usr/share/doc/ruby-jquery-scrollto-rails/ruby-jquery-scrollto-rails.ps.gz

Format: text
Files: /usr/share/doc/ruby-jquery-scrollto-rails/ruby-jquery-scrollto-rails.text.gz

Format: HTML
Index: /usr/share/doc/ruby-jquery-scrollto-rails/html/index.html
Files: /usr/share/doc/ruby-jquery-scrollto-rails/html/*.html
